export default {
  ADD_CURRENT_STORIE: "ADD_CURRENT_STORIE",
  ADD_COMENTS: "ADD_COMMENTS",
  DELETE_COMENTS: "DELETE_COMMENTS",
  REFRESH_COMENTS: "REFRESH_COMMENTS",
  ADD_NEWS_IDS: "ADD_NEWS_IDS",
  ADD_NEWS: "ADD_NEWS",
  DATA_LOADING: "LOADING",
  DATA_LOADED: "LOADED",
};
